app:
  name: uni-deploy

replicaCount: 2

image: 
  repository: nmc9812/uni
  tag: v1.1.0

ports:
  containerPort: 3000
  appPort: 83

parameter:
  server: 10.0.1.27
  share: /var/nfs/general/uni

statefull:
  replicaCount: 2
  port: 
  containerPort: 3306