version: '3.9'

networks:
  mynet:

volumes:
  mariadb:

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - mynet
    volumes:
      - mariadb:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro


  uni:
    image: 
    container_name: universityapp
    ports:
      - 3001:3000
    env_file:
      - .env
    networks:
      - mynet
    depends_on:
      - mariadb
    

    