image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: 26
  pullPolicy: Always

auth:
  adminUser: nmc
  adminPassword: "helloguys"

service:
  type: NodePort
  nodePorts:
    http: 30080

proxy: edge

postgresql:
  enabled: true
  persistence:
    storageClass: "nfs-csi-uni" 
    size: 8Gi