apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: uni-grant
  namespace: uni-ns
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: noel-ns
  to:
    - group: ""
      kind: Service


---
apiVersion: v1
kind: Secret
metadata:
  name: uni-secret
  namespace: uni-ns
stringData:
  DB_USER: college_user
  DB_PASSWORD: deereddy@123
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: mariadb
  GRIEVANCE_DB: grievance_db
  LEAVE_DB: leave_db
  TIMETABLE_DB: timetable_db
  EXAMS_DB: exams_db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
  namespace: uni-ns
  labels:
    app: uni
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: uni
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: uni
    spec:
      containers:
        - name: uni-container
          image: {{.Values.image.repository}}: {{.Values.image.tag}}
          ports: {{.Values.ports.containerPorts}}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: DB_PORT
            - name: GRIEVANCE_DB
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: GRIEVANCE_DB
            - name: LEAVE_DB
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: LEAVE_DB
            - name: TIMETABLE_DB
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: TIMETABLE_DB
            - name: EXAMS_DB
              valueFrom:
                secretKeyRef:
                  name: uni-secret
                  key: EXAMS_DB
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"

---


apiVersion: v1
kind: Service
metadata:
  name: uni-service
  namespace: uni-ns
spec:
  selector:
    app: uni
  ports:
    - port: 83
      targetPort: 3000
  type: NodePort


