name: CI-CD Pipeline

on:
  push:
    branches:
      - develop
      - master

jobs:
  # JOB 1: CI (Develop)
  ci:
    name: Validate Code (Develop)
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=noelmc-ust
            -Dsonar.projectKey=noelmc-ust_Duniversity-College-Portal
            -Dsonar.qualitygate.wait=true
    
      - name: Docker Build Test
        run: docker build -t validation-image:${{ github.sha }} .

  # JOB 2: CD (Master)
  cd:
    name: Build & Push Docker Image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    # Define image name here so all steps can see it easily
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/app 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest

      - name: Scan Image (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          exit-code: '1' 
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest